#!/bin/bash

# Comparaison des performances des modèles WhisperX

echo "🎙️ COMPARAISON DES MODÈLES WHISPERX - INTERFACE VOCALE INSTANTANÉE"
echo "=================================================================="
echo ""
echo "📊 RÉSUMÉ DES MODÈLES DISPONIBLES:"
echo ""

echo "1. 🏃‍♂️ TINY (39 MB)"
echo "   ├─ Vitesse: ⭐⭐⭐⭐⭐ (Très rapide)"
echo "   ├─ Précision: ⭐⭐ (Basique)"
echo "   ├─ Usage RAM: ⭐⭐⭐⭐⭐ (Très faible)"
echo "   ├─ Latence: ~50-100ms"
echo "   └─ Idéal pour: Tests, démonstrations, utilisation basique"
echo ""

echo "2. 🚀 SMALL (244 MB)"
echo "   ├─ Vitesse: ⭐⭐⭐⭐ (Rapide)"
echo "   ├─ Précision: ⭐⭐⭐ (Bonne)"
echo "   ├─ Usage RAM: ⭐⭐⭐⭐ (Faible)"
echo "   ├─ Latence: ~100-200ms"
echo "   └─ Idéal pour: Usage quotidien, bon compromis"
echo ""

echo "3. 🎯 MEDIUM (769 MB)"
echo "   ├─ Vitesse: ⭐⭐⭐ (Modérée)"
echo "   ├─ Précision: ⭐⭐⭐⭐ (Très bonne)"
echo "   ├─ Usage RAM: ⭐⭐⭐ (Modérée)"
echo "   ├─ Latence: ~200-400ms"
echo "   └─ Idéal pour: Dictée, transcription importante"
echo ""

echo "4. 🏆 LARGE-V3 (1550 MB)"
echo "   ├─ Vitesse: ⭐⭐ (Plus lente)"
echo "   ├─ Précision: ⭐⭐⭐⭐⭐ (Excellente)"
echo "   ├─ Usage RAM: ⭐⭐ (Élevée)"
echo "   ├─ Latence: ~400-800ms"
echo "   └─ Idéal pour: Qualité professionnelle, transcription critique"
echo ""

echo "=================================================================="
echo "🎮 COMMANDES DE LANCEMENT:"
echo ""
echo "• Modèle TINY:     ./run_instantaneous_voice.sh"
echo "• Modèle SMALL:    ./run_instantaneous_voice_small.sh"
echo "• Modèle MEDIUM:   ./run_instantaneous_voice_medium.sh"
echo "• Modèle LARGE:    ./run_instantaneous_voice_large.sh"
echo "• Sélecteur:       ./select_voice_model.sh"
echo ""

echo "=================================================================="
echo "💡 RECOMMANDATIONS D'USAGE:"
echo ""
echo "🔬 Pour des tests rapides -> TINY"
echo "💼 Pour un usage quotidien -> SMALL"
echo "📝 Pour la dictée professionnelle -> MEDIUM"
echo "🎓 Pour la transcription académique -> LARGE"
echo ""

echo "🔧 STATUT ACTUEL:"
echo "• ✅ TINY: Prêt (déjà téléchargé)"
echo "• ✅ SMALL: Prêt (téléchargé)"
echo "• ✅ MEDIUM: Prêt (téléchargé)"
echo "• ⏳ LARGE: Sera téléchargé au premier lancement (~1.5 GB)"
